### ISSUE TITLE
Updating user fails when not adding an email.

### ISSUE THREAD

**Issue by ronthepennyhoarder** [alexkahn/iterable-api#17]
In my use case, I am only using iterable for phone numbers, I am not collecting email addresses. This means that the email address parameter to create a new user is always going to be None. Using your function to create a new user results in the following error:
`{'msg': 'Invalid email: none', 'code': 'InvalidEmailAddressError', 'params': None}`. The API docs also state that you should provide the email or the userId, not both.

There is also no support for the `preferUserId` parameter that is outlined in their API docs. https://api.iterable.com/api/docs#users_updateUser

You can fix this by checking to see if email and userId parameter is None and not include that parameter in the payload and add some additional parameters to the function to to support the other options.

```
 def update(self, email=None, data_fields=None, user_id=None, merge_nested_objects=None, preferUserId=false):
        resource = "/api/users/update"
        payload = {}
        if email is not None:
                payload["email"] = str(email)
        payload["dataFields"] = data_fields
        if user_id is not None:
                payload["userId"] = str(user_id)
        payload["mergeNestedObjects"] = merge_nested_objects
        payload["preferUserId"] = preferUserId
        return self.client.post(resource, data=payload)
```

**Comment by alexkahn** [comment]
Closed with #16
