### ISSUE TITLE
Will not import within Jupyter notebook

### ISSUE THREAD

**Issue by ga1205** [alexkahn/iterable-api#7]
`from iterable import Iterable` results in the error:

`ModuleNotFoundError: No module named 'iterable'` even though it was already installed with pip (and kernel restarted).  

Python version: 3.9.13
MacOS Monterey with M1 Pro Max Chip

**Comment by alexkahn** [comment]
I'm not sure what your setup looks like but if you can confirm that jupyter and this package are installed in the same virtualenv or the analogous setup for whatever you're using then I'll be happy to look into it further.
